version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: ${APP_SPARROW_BROADCAST_POOL_IP}
      APP_PORT: ${APP_SPARROW_BROADCAST_POOL_PORT}

  init:
    image: alpine:3.20
    user: "0:0"
    restart: "no"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command: ["sh", "-c", "mkdir -p /data && chown -R 1000:1000 /data && chmod 755 /data"]

  web:
    image: ghcr.io/criptoworld8484/broadcast-pool-umbrel:0.3.16
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      init:
        condition: service_completed_successfully
    ports:
      - "0.0.0.0:50050:50050/tcp"
    volumes:
      - ${APP_DATA_DIR}/data:/home/app/data
    environment:
      BROADCAST_POOL_DATA_DIR: "/home/app/data"
      BROADCAST_POOL_NETWORK: "${APP_BITCOIN_NETWORK:-mainnet}"
      BROADCAST_POOL_RPC_URL: "http://${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT}"
      BROADCAST_POOL_RPC_USER: "${APP_BITCOIN_RPC_USER}"
      BROADCAST_POOL_RPC_PASS: "${APP_BITCOIN_RPC_PASS}"
      APP_ELECTRS_NODE_IP: "${APP_ELECTRS_NODE_IP}"
      APP_ELECTRS_NODE_PORT: "${APP_ELECTRS_NODE_PORT}"
      APP_ELECTRS_NODE_SSL_PORT: "${APP_ELECTRS_NODE_SSL_PORT}"
      BROADCAST_POOL_LAN_IP: "${APP_SPARROW_BROADCAST_POOL_LAN_IP:-}"
      BROADCAST_POOL_UMBREL: "1"
      BROADCAST_POOL_WEB_HOST: "0.0.0.0"
      BROADCAST_POOL_WEB_PORT: "8080"
      BROADCAST_POOL_ELECTRUM_HOST: "0.0.0.0"
      BROADCAST_POOL_ELECTRUM_PORT: "50050"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      default:
        ipv4_address: ${APP_SPARROW_BROADCAST_POOL_IP}
