version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: sparrow-frigate_frigate_1
      APP_PORT: 50001

  frigate:
    image: ghcr.io/criptoworld8484/frigate-umbrel/frigate-umbrel:latest
    init: true
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "50001:50001"
      - "50002:50002"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      FRIGATE_HOME: /data
      FRIGATE_NETWORK: testnet4