pid /tmp/nginx/nginx.pid;
worker_processes 1;
error_log /tmp/nginx/error.log warn;

events {
    worker_connections 256;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /tmp/nginx/access.log;
    include /etc/nginx/conf.d/*.conf;
}
